-- Tabela de eventos (issue #42 / spec #39): o contrato de dados entre
-- scraper, API e site. SQL portável entre Postgres (testes/produção) e
-- H2 em memória (esqueleto de runtime, ver application.yml).

CREATE TABLE events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR NOT NULL,
    description      TEXT,
    starts_at        TIMESTAMP NOT NULL,
    venue            VARCHAR,
    city             VARCHAR,
    uf               VARCHAR,
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    registration_url VARCHAR,
    source           VARCHAR NOT NULL,
    banner_url       VARCHAR
);

-- Tags do evento (issue #42): coleção de strings associada ao evento.
CREATE TABLE event_tags (
    event_id BIGINT NOT NULL,
    tag      VARCHAR NOT NULL,
    PRIMARY KEY (event_id, tag),
    CONSTRAINT fk_event_tags_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);
